# app/config/routing.yml

#PREFIX POUR LA PLATFORM D'ANNONCES
ml_platform:
    resource: "@MLPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

#SURCHARGE BUNDLE FOSUserBundle
#m_lmy_user:
#    resource: "@MLmyUserBundle/Resources/config/routing.yml"
#    path:   /

#BUNDLE par défaut (affichage principal du site)
app:
    resource: '@AppBundle/Controller/'
    type: annotation
#    path: /

#FOSUserBundle
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"